version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    volumes:
      - namenode:/hadoop/dfs/name
      - ../../test_data/batch.csv:/batch.csv:ro
    environment:
      - CLUSTER_NAME=asvsp
    env_file:
      - ./config.env
    ports:
      - 9870:9870
      - 9000:9000
    networks:
      - cluster

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    volumes:
      - datanode1:/hadoop/dfs/data
    env_file:
      - ./config.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    networks:
      - cluster

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    volumes:
      - datanode2:/hadoop/dfs/data
    env_file:
      - ./config.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    networks:
      - cluster

  spark-master:
    image: bde2020/spark-master:3.0.1-hadoop3.2
    container_name: spark-master
    volumes:
      - ../scripts/spark/event_window.py:/event_window.py:ro
      - ../scripts/spark/user_behavior.py:/user_behavior.py:ro
      - ../scripts/spark/price_variation.py:/price_variation.py:ro
      - ../../stream/consumer/main.py:/consumer.py:ro
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      - PYSPARK_PYTHON=python3
    env_file:
      - ./config.env
    networks:
      - cluster

  spark-worker1:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker1
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - 8081:8081
    env_file:
      - ./config.env
    networks:
      - cluster

  spark-worker2:
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    container_name: spark-worker2
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - 8082:8081
    env_file:
      - ./config.env
    networks:
      - cluster

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    env_file:
      - ./config.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
    networks:
      - cluster

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    env_file:
      - ./config.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode1:9864 datanode2:9864 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
    networks:
      - cluster

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore-postgresql
    networks:
      - cluster

  superset:
    build: ../superset/
    container_name: superset
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_EMAIL=satelit1312srbija@gmail.com
      - ADMIN_PASSWORD=admin
      - HIVE_CONNECTION=hive://hive@hive-server:10000/default
    ports:
      - "8088:8088"
    networks:
      - cluster

volumes:
  namenode:
  datanode1:
  datanode2:

networks:
  cluster:
    external: true
